<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SongSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('songs')->insert([
            [ 'title' => 'Supermodel', 'artist' => 'RuPaul'],
            [ 'title' => 'We Break The Dawn', 'artist' => 'Michelle Williams'],
            [ 'title' => 'The Greatest Love Of All', 'artist' => 'Whitney Houston'],
            [ 'title' => 'Would I Lie To You', 'artist' => 'Eurythmics'],
            [ 'title' => 'Stronger', 'artist' => 'Britney Spears'],
            [ 'title' => 'Shackles (Praise You)', 'artist' => 'Mary Mary'],
            [ 'title' => 'Cover Girl', 'artist' => 'RuPaul'],
            [ 'title' => 'My Lovin\' (You\'re Never Gonna Get It)', 'artist' => 'En Vogue'],
            [ 'title' => 'I Hear You Knocking', 'artist' => 'Wynnona Judd'],
            [ 'title' => 'Two of Hearts', 'artist' => 'Stacey Q'],
            [ 'title' => 'Carry On', 'artist' => 'Martha Wash'],
            [ 'title' => 'Black Velvet', 'artist' => 'Alannah Myles'],
            [ 'title' => 'He\'s The Greatest Dancer', 'artist' => 'Sister Sledge'],
            [ 'title' => 'Shake Your Love', 'artist' => 'Debbie Gibson'],
            [ 'title' => 'Something He Can Feel', 'artist' => 'Aretha Franklin'],
            [ 'title' => 'Jealous of My Boogie', 'artist' => 'RuPaul'],
            [ 'title' => 'The Right Stuff', 'artist' => 'Vanessa Williams'],
            [ 'title' => 'Bad Romance', 'artist' => 'Lady Gaga'],
            [ 'title' => 'Don\'t Leave Me This Way', 'artist' => 'Thelma Houston'],
            [ 'title' => 'Meeting in the Ladies Room', 'artist' => 'Klymaxx'],
            [ 'title' => 'Looking For A New Love', 'artist' => 'Jody Watley'],
            [ 'title' => 'Knock On Wood', 'artist' => 'Amii Stewart'],
            [ 'title' => 'MacArthur Park', 'artist' => 'Donna Summer'],
            [ 'title' => 'Hey Mickey', 'artist' => 'Toni Basil'],
            [ 'title' => 'Believe', 'artist' => 'Cher'],
            [ 'title' => 'Even Angels', 'artist' => 'Fantasia'],
            [ 'title' => 'Straight Up', 'artist' => 'Paula Abdul'],
            [ 'title' => 'I Think About You', 'artist' => 'Patti LaBelle'],
            [ 'title' => 'Champion', 'artist' => 'RuPaul'],
            [ 'title' => 'Toxic', 'artist' => 'Britney Spears'],
            [ 'title' => 'Bad Girls', 'artist' => 'Donna Summer'],
            [ 'title' => 'This Will Be (An Everlasting Love)', 'artist' => 'Natalie Cole'],
            [ 'title' => 'Trouble', 'artist' => 'P!nk'],
            [ 'title' => 'Vogue', 'artist' => 'Madonna'],
            [ 'title' => 'Born This Way', 'artist' => 'Lady Gaga'],
            [ 'title' => 'Mi Vida Loca', 'artist' => 'Pam Tillis'],
            [ 'title' => 'It\'s Raining Men (The Sequel)', 'artist' => 'Martha Wash and RuPaul'],
            [ 'title' => 'I\'ve Got To Use My Imagination', 'artist' => 'Gladys Knight'],
            [ 'title' => '(You Make Me Feel Like) A Natural Woman', 'artist' => 'Aretha Franklin'],
            [ 'title' => 'No One Else On Earth', 'artist' => 'Wynnona Judd'],
            [ 'title' => 'Glamazon', 'artist' => 'RuPaul'],
            [ 'title' => 'Party in the U.S.A', 'artist' => 'Miley Cyrus'],
            [ 'title' => 'Only Girl (In The World)', 'artist' => 'Rihanna'],
            [ 'title' => 'When I Grow Up', 'artist' => 'Pussycat Dolls'],
            [ 'title' => 'Oops!...I Did It Again', 'artist' => 'Britney Spears'],
            [ 'title' => 'Take Me Home', 'artist' => 'Cher'],
            [ 'title' => 'I\'m So Excited', 'artist' => 'The Pointer Sisters'],
            [ 'title' => 'Whip My Hair', 'artist' => 'Willow Smith'],
            [ 'title' => 'Ain\'t Nothin\' Going on but the Rent', 'artist' => 'Gwen Guthrie'],
            [ 'title' => 'Cold Hearted', 'artist' => 'Paula Abdul'],
            [ 'title' => '(It Takes) Two To Make It Right', 'artist' => 'Seduction'],
            [ 'title' => 'Malambo No. 1', 'artist' => 'Yma Sumac'],
            [ 'title' => 'The Beginning', 'artist' => 'RuPaul'],
            [ 'title' => 'Express Yourself', 'artist' => 'Madonna'],
            [ 'title' => 'Turn The Beat Around', 'artist' => 'Vicky Sue Robinson'],
            [ 'title' => 'Shake it Up', 'artist' => 'Selena Gomez'],
            [ 'title' => 'I\'m Every Woman', 'artist' => 'Chaka Khan'],
            [ 'title' => 'Head to Toe', 'artist' => 'Lisa Lisa & Cult Jam'],
            [ 'title' => 'Whatta Man', 'artist' => 'Salt-n-Pepa feat. En Vogue'],
            [ 'title' => 'Point of No Return', 'artist' => 'Exposé'],
            [ 'title' => 'Stupid Girls', 'artist' => 'P!nk'],
            [ 'title' => 'Vibeology', 'artist' => 'Paula Abdul'],
            [ 'title' => 'Think', 'artist' => 'Aretha Franklin'],
            [ 'title' => 'Stronger (What Doesn\'t Kill You)', 'artist' => 'Kelly Clarkson'],
            [ 'title' => 'Sissy That Walk', 'artist' => 'RuPaul'],
            [ 'title' => 'Geronimo', 'artist' => 'RuPaul'],
            [ 'title' => 'Twist of Fate', 'artist' => 'Olivia Newton-John'],
            [ 'title' => 'I Was Gonna Cancel', 'artist' => 'Kylie Minogue'],
            [ 'title' => 'Dreaming', 'artist' => 'Blondie'],
            [ 'title' => 'Lovergirl', 'artist' => 'Teena Marie'],
            [ 'title' => 'Break Free', 'artist' => 'Ariana Grande'],
            [ 'title' => 'No More Lies', 'artist' => 'Michel\'le'],
            [ 'title' => 'I Think We\'re Alone Now', 'artist' => 'Tiffany'],
            [ 'title' => 'Really Don\'t Care', 'artist' => 'Demi Lovato'],
            [ 'title' => 'Show Me Love', 'artist' => 'Robin S.'],
            [ 'title' => 'Roar', 'artist' => 'Katy Perry'],
            [ 'title' => 'Born Naked', 'artist' => 'RuPaul'],
            [ 'title' => 'Applause', 'artist' => 'Lady Gaga'],
            [ 'title' => 'I Will Survive', 'artist' => 'Gloria Gaynor'],
            [ 'title' => 'Mesmerized', 'artist' => 'Faith Evans'],
            [ 'title' => 'Call Me', 'artist' => 'Blondie'],
            [ 'title' => 'Causing A Commotion', 'artist' => 'Madonna'],
            [ 'title' => 'I Don\'t Care', 'artist' => 'Icona Pop'],
            [ 'title' => 'And I Am Telling You I\'m Not Going', 'artist' => 'Jennifer Holliday'],
            [ 'title' => 'You Make Me Feel (Mighty Real)', 'artist' => 'Sylvester'],
            [ 'title' => 'The Realness', 'artist' => 'RuPaul'],
            [ 'title' => 'Love Shack', 'artist' => 'The B-52\'s'],
            [ 'title' => 'Holding Out For A Hero', 'artist' => 'Bonnie Tyler'],
            [ 'title' => 'I Wanna Go', 'artist' => 'Britney Spears'],
            [ 'title' => 'Woman Up', 'artist' => 'Meghan Trainor'],
            [ 'title' => 'Music', 'artist' => 'Madonna'],
            [ 'title' => 'Finally', 'artist' => 'Cece Peniston'],
            [ 'title' => 'Baby I\'m Burnin\'', 'artist' => 'Dolly Parton'],
            [ 'title' => 'Greedy', 'artist' => 'Ariana Grande'],
            [ 'title' => 'Cool For The Summer', 'artist' => 'Demi Lovato'],
            [ 'title' => 'Macho Man', 'artist' => 'The Village People'],
            [ 'title' => 'U Wear It Well', 'artist' => 'RuPaul'],
            [ 'title' => 'So Emotional', 'artist' => 'Whitney Houston'],
            [ 'title' => 'It\'s Not Right But It\'s Okay', 'artist' => 'Whitney Houston'],
            [ 'title' => 'Ain\'t No Other Man', 'artist' => 'Christina Aguilera'],
            [ 'title' => 'Best Of My Love', 'artist' => 'The Emotions'],
            [ 'title' => 'Celebrity Skin', 'artist' => 'Hole'],
            [ 'title' => 'Pound The Alarm', 'artist' => 'Nicki Minaj'],
            [ 'title' => 'Man! I Feel Like A Woman', 'artist' => 'Shania Twain'],
            [ 'title' => 'I\'m Coming Out', 'artist' => 'Diana Ross'],
            [ 'title' => 'Cut To The Feeling', 'artist' => 'Carly Rae Jepsen'],
            [ 'title' => 'Groove Is In The Heart', 'artist' => 'Deee-Lite'],
            [ 'title' => 'New Attitude', 'artist' => 'Patti LaBelle'],
            [ 'title' => 'Good As Hell', 'artist' => 'Lizzo'],
            [ 'title' => 'Nasty Girl', 'artist' => 'Vanity 6'],
            [ 'title' => 'Call Me Mother', 'artist' => 'RuPaul'],
            [ 'title' => 'Nasty', 'artist' => 'Janet Jackson'],
            [ 'title' => 'If', 'artist' => 'Janet Jackson'],
            [ 'title' => 'Bang Bang', 'artist' => 'Jessie J, Ariana Grande and Nicki Minaj'],
            [ 'title' => 'Best of Both Worlds', 'artist' => 'Hannah Montana'],
            [ 'title' => 'Work Bitch', 'artist' => 'Britney Spears'],
            [ 'title' => 'Waiting For Tonight', 'artist' => 'Jennifer Lopez'],
            [ 'title' => 'Living in America', 'artist' => 'James Brown'],
            [ 'title' => 'I\'m Your Baby Tonight', 'artist' => 'Whitney Houston'],
            [ 'title' => 'Last Dance', 'artist' => 'Donna Summer'],
            [ 'title' => 'Strut', 'artist' => 'Sheena Easton'],
            [ 'title' => 'Sorry Not Sorry', 'artist' => 'Demi Lovato'],
            [ 'title' => 'Hood Boy', 'artist' => 'Fantasia'],
            [ 'title' => 'No More Drama', 'artist' => 'Mary J. Blige'],
            [ 'title' => 'No Scrubs', 'artist' => 'TLC'],
            [ 'title' => 'Pride: A Deeper Love', 'artist' => 'Aretha Franklin'],
            [ 'title' => 'Bootylicious', 'artist' => 'Destiny\'s Child'],
            [ 'title' => 'SOS', 'artist' => 'Rihanna'],
            [ 'title' => 'The Edge of Glory', 'artist' => 'Lady Gaga'],
            [ 'title' => 'Starships', 'artist' => 'Nicki Minaj'],
            [ 'title' => 'Call Your Girlfriend', 'artist' => 'Robyn'],
            [ 'title' => 'Problem', 'artist' => 'Ariana Grande and Iggy Azalea'],
            [ 'title' => 'S&M', 'artist' => 'Rihanna'],
            [ 'title' => 'Heart to Break', 'artist' => 'Kim Petras'],
            [ 'title' => 'Let It Go', 'artist' => 'Caissie Levy'],
            [ 'title' => 'Burning Up', 'artist' => 'Madonna'],
            [ 'title' => 'This Is My Night', 'artist' => 'Chaka Khan'],
            [ 'title' => 'Firework', 'artist' => 'Katy Perry'],
            [ 'title' => 'Kill The Lights', 'artist' => 'Alex Newell'],
            [ 'title' => '1999', 'artist' => 'Prince'],
            [ 'title' => 'On The Floor', 'artist' => 'Jennifer Lopez and Pitbull'],
            [ 'title' => 'Bring Back My Girls', 'artist' => 'RuPaul'],
            [ 'title' => 'Survivor', 'artist' => 'Destiny\'s Child'],
            [ 'title' => 'Call Me Maybe', 'artist' => 'Carly Rae Jepsen'],
            [ 'title' => 'The Pleasure Principle', 'artist' => 'Janet Jackson'],
            [ 'title' => 'Rumors', 'artist' => 'Lindsay Lohan'],
            [ 'title' => 'Ex\'s & Oh\'s', 'artist' => 'Elle King'],
            [ 'title' => 'Lady Marmalade', 'artist' => 'Christina Aguilera, Lil\' Kim, Mya & Pink'],
            [ 'title' => 'Break My Heart', 'artist' => 'Dua Lipa'],
            [ 'title' => 'If U Seek Amy', 'artist' => 'Britney Spears'],
            [ 'title' => '100% Pure Love', 'artist' => 'Crystal Waters'],
            [ 'title' => 'Fancy', 'artist' => 'Iggy Azalea and Charli XCX'],
            [ 'title' => 'Hit \'Em Up Style (Oops!)', 'artist' => 'Blue Cantrell'],
            [ 'title' => 'Whole Lotta Woman', 'artist' => 'Kelly Clarkson'],
            [ 'title' => 'BO$$', 'artist' => 'Fifth Harmony'],
            [ 'title' => 'Fascinated', 'artist' => 'Company B'],
            [ 'title' => 'My Humps', 'artist' => 'Black Eyed Peas'],
            [ 'title' => 'No Tears Left To Cry', 'artist' => 'Ariana Grande'],
            [ 'title' => 'Strong Enough', 'artist' => 'Cher'],
            [ 'title' => 'I Learned from the Best', 'artist' => 'Whitney Houston'],
            [ 'title' => 'Gimme More', 'artist' => 'Britney Spears'],
            [ 'title' => 'Till the World Ends', 'artist' => 'Britney Spears'],
            [ 'title' => 'Turn Me On', 'artist' => 'David Guetta and Nicki Minaj'],
            [ 'title' => 'Ignorance', 'artist' => 'Paramore'],
            [ 'title' => 'Tightrope', 'artist' => 'Janelle Monae'],
            [ 'title' => 'In The Next Life', 'artist' => 'Kim Petras'],
            [ 'title' => 'Dancing Queen', 'artist' => 'ABBA'],
            [ 'title' => 'Bring Me To Life', 'artist' => 'Evanescence'],
            [ 'title' => 'Sk8er Boi', 'artist' => 'Avril Lavigne'],
            [ 'title' => 'Kiss', 'artist' => 'Prince'],
            [ 'title' => 'Hung Up', 'artist' => 'Madonna'],
            [ 'title' => 'Cannibal', 'artist' => 'Kesha'],
            [ 'title' => 'Candyman', 'artist' => 'Christina Aguilera'],
            [ 'title' => 'Bohemian Rhapsody', 'artist' => 'Queen'],
            [ 'title' => 'Venus', 'artist' => 'Lady Gaga'],
            [ 'title' => 'Hair', 'artist' => 'Lady Gaga'],
            [ 'title' => 'Dancing Queen', 'artist' => 'ABBA'],
            [ 'title' => 'STFU', 'artist' => 'Rina Sawayama'],
            [ 'title' => 'HOT HOT', 'artist' => 'Bree Runway'],
            [ 'title' => 'I Can Love You', 'artist' => 'Mary J. Blige and Lil Kim'],
            [ 'title' => 'Superbass', 'artist' => 'Nicki Minaj'],
            [ 'title' => 'Can\'t Get You Out of My Head', 'artist' => 'Kylie Minogue'],
            [ 'title' => 'Misery Business', 'artist' => 'Paramore'],
            [ 'title' => 'The Promise', 'artist' => 'Girls Aloud'],
            [ 'title' => 'Star Love', 'artist' => 'Cheryl Lynn'],
            [ 'title' => 'Freeway of Love', 'artist' => 'Aretha Franklin'],
            [ 'title' => 'Tell It To My Heart', 'artist' => 'Taylor Dayne'],
            [ 'title' => 'Don\'t Rush Me', 'artist' => 'Taylor Dayne'],
            [ 'title' => 'Dirrty', 'artist' => 'Christina Aguilera'],
            [ 'title' => '34+35', 'artist' => 'Ariana Grande'],
            [ 'title' => 'Barbie Girl', 'artist' => 'Aqua'],
            [ 'title' => 'Va Va Voom', 'artist' => 'Nicki Minaj'],
            [ 'title' => 'Hallucinate', 'artist' => 'Dua Lipa'],
            [ 'title' => 'Bubblegum Bitch', 'artist' => 'MARINA'],
            [ 'title' => 'Boss Bitch', 'artist' => 'Doja Cat'],
            [ 'title' => 'Hopelessly Devote to You', 'artist' => 'Olivia Newton John'],
            [ 'title' => 'Your Disco Needs You', 'artist' => 'Kylie Minogue'],
            [ 'title' => 'Froot', 'artist' => 'MARINA'],
            [ 'title' => 'She Works Hard For The Money', 'artist' => 'Donna Summer'],
            [ 'title' => 'Supernova', 'artist' => 'Carly Rae Jepsen'],
            [ 'title' => 'Detention', 'artist' => 'Melanie Martinez'],
            [ 'title' => 'Complicated', 'artist' => 'Avril Lavigne'],
            [ 'title' => 'So What', 'artist' => 'P!nk'],
            [ 'title' => 'Good 4 U', 'artist' => 'Olivia Rodrigo'],
            [ 'title' => 'Take A Chance On Me', 'artist' => 'ABBA'],
            [ 'title' => 'Casanova', 'artist' => 'Allie X'],
            [ 'title' => 'TIk Tok', 'artist' => 'Kesha'],
            [ 'title' => 'Heart of Glass', 'artist' => 'Blondie'],
            [ 'title' => 'When I Think of You', 'artist' => 'Janet Jackson'],
            [ 'title' => 'Prisoner', 'artist' => 'Miley Cyrus (ft. Dua Lipa)'],
            [ 'title' => 'Homemade Dynamite', 'artist' => 'Lorde'],
            [ 'title' => 'claws', 'artist' => 'Charli XCX'],
            [ 'title' => 'NASA', 'artist' => 'Ariana Grande'],
            [ 'title' => 'Say So', 'artist' => 'Doja Cat'],
            [ 'title' => 'Captain Hook', 'artist' => 'Megan Thee Stallion'],
            [ 'title' => 'Pynk', 'artist' => 'Janelle Monaé (ft. Grimes)'],
            [ 'title' => 'Into the Groove', 'artist' => 'Madonna'],
            [ 'title' => 'Cool Girl', 'artist' => 'Tove Lo'],
            [ 'title' => 'Break The Ice', 'artist' => 'Britney Spears'],
            [ 'title' => 'Still Into You', 'artist' => 'Paramore'],
            [ 'title' => 'Vroom Vroom', 'artist' => 'Charli XCX'],
            [ 'title' => 'XS', 'artist' => 'Rina Sawayama'],
            [ 'title' => 'Teenage Dream', 'artist' => 'Katy Perry'],
            [ 'title' => 'Unwritten', 'artist' => 'Natasha Bedingfield'],
            [ 'title' => 'Hollaback Girl', 'artist' => 'Gwen Stefani'],
            [ 'title' => 'Miss You Much', 'artist' => 'Janet Jackson'],
            [ 'title' => 'I Feel Love', 'artist' => 'Donna Summer'],
            [ 'title' => 'Don\'t Stop The Music', 'artist' => 'Rihanna'],
            [ 'title' => 'Love On The Brain', 'artist' => 'Rihanna'],
            [ 'title' => 'Valerie', 'artist' => 'Amy Winehouse'],
            [ 'title' => 'Killer Queen', 'artist' => 'Queen'],
            [ 'title' => 'Ribs', 'artist' => 'Lorde'],
            [ 'title' => 'Solar Power', 'artist' => 'Lorde'],
            [ 'title' => 'Jerome', 'artist' => 'Lizzo'],
            [ 'title' => 'Kinky', 'artist' => 'Kesha'],
            [ 'title' => 'G.U.Y', 'artist' => 'Lady Gaga'],
            [ 'title' => 'Waka Waka (This Time For Africa)', 'artist' => 'Shakira'],
            [ 'title' => 'Dangerous Woman', 'artist' => 'Ariana Grande'],
            [ 'title' => 'Whenever, Wherever', 'artist' => 'Shakira'],
            [ 'title' => 'Lowlife', 'artist' => 'Poppy'],
            [ 'title' => 'Conqueror', 'artist' => 'Estelle'],
            [ 'title' => 'Dynasty', 'artist' => 'Rina Sawayama'],
            [ 'title' => 'Fergalicious', 'artist' => 'Fergie'],
            [ 'title' => 'Meet Me Halfway', 'artist' => 'Black Eyed Peas'],
            [ 'title' => 'I Say A Little Prayer', 'artist' => 'Aretha Franklin'],
            [ 'title' => 'Aura', 'artist' => 'Lady Gaga'],
            [ 'title' => 'Now That You Got It', 'artist' => 'Gwen Stefani'],
            [ 'title' => 'Skyfall', 'artist' => 'Adele'],
            [ 'title' => 'Back To Black', 'artist' => 'Amy Winehouse'],
            [ 'title' => 'Tears Dry On Their Own', 'artist' => 'Amy Winehouse'],
            [ 'title' => 'Seven Wonders', 'artist' => 'Fleetwood Mac'],
            [ 'title' => 'Baby One More Time', 'artist' => 'Britney Spears'],
            [ 'title' => 'Naked', 'artist' => 'Ava Max'],
            [ 'title' => 'A Little Party Never Killed Nobody', 'artist' => 'Fergie'],
            [ 'title' => 'Tears', 'artist' => 'Clean Bandit'],
            [ 'title' => 'Work', 'artist' => 'Kelly Rowland'],
            [ 'title' => 'Say My Name', 'artist' => 'Tove Styrke'],
            [ 'title' => 'Do It', 'artist' => 'Chloe X Halle'],
            [ 'title' => 'Like A Virgin', 'artist' => 'Madonna'],
            [ 'title' => 'Chun Li', 'artist' => 'Nicki Minaj'],
            [ 'title' => 'ATM', 'artist' => 'Bree Runway'],
            [ 'title' => 'Star Love', 'artist' => 'Cheryl Lynn'],
            [ 'title' => 'Express', 'artist' => 'Christina Aguillera'],
            [ 'title' => 'Kill V. Main', 'artist' => 'Grimes'],
            [ 'title' => 'Taki Taki', 'artist' => 'DJ Snake (ft. Selena Gomez, Cardi B)'],
            [ 'title' => 'Black Cat', 'artist' => 'Janet Jackson'],
            [ 'title' => 'Tainted Love', 'artist' => 'Gloria Jones'],
            [ 'title' => 'Private Dancer', 'artist' => 'Tina Turner'],
            [ 'title' => 'Sweet Dreams', 'artist' => 'Beyoncé'],
            [ 'title' => 'Kiss Me More', 'artist' => 'Doja Cat (ft. SZA)'],
            [ 'title' => 'Take A Chance On Me', 'artist' => 'ABBA'],
            [ 'title' => 'Mine', 'artist' => 'Slayyyter'],
            [ 'title' => 'Baby One More Time', 'artist' => 'Britney Spears'],
            [ 'title' => 'Troubled Paradise', 'artist' => 'Slayyyter'],
            [ 'title' => 'Swine', 'artist' => 'Lady Gaga'],
            [ 'title' => 'Vacation', 'artist' => 'GRL'],
            [ 'title' => 'Alive', 'artist' => 'SIA'],
            [ 'title' => 'Now That I Found You', 'artist' => 'Carly Rae Jepsen'],
            [ 'title' => 'IDGAF', 'artist' => 'Dua Lipa'],
            [ 'title' => 'In My Bed', 'artist' => 'Amy Winehouse'],
            [ 'title' => 'Get Outta My Way', 'artist' => 'Kylie Minogue'],
            [ 'title' => 'I Drove All Night', 'artist' => 'Celine Dion'],
            [ 'title' => 'Bad Bitch Tip', 'artist' => 'LaLa Ri'],
            [ 'title' => 'Run The World (Girls)', 'artist' => 'Beyoncé'],
            [ 'title' => 'Focus', 'artist' => 'Charli XCX'],
            [ 'title' => 'Judas', 'artist' => 'Lady Gaga'],
            [ 'title' => 'Circus', 'artist' => 'Britney Spears'],
            [ 'title' => 'Buttons', 'artist' => 'The Pussycat Dolls'],
            [ 'title' => 'Venom', 'artist' => 'Slayyyter'],
            [ 'title' => 'Shut Up And Drive', 'artist' => 'Rihanna'],
            [ 'title' => 'Dollhouse', 'artist' => 'Melanie Martinez'],
            [ 'title' => 'Brick', 'artist' => 'Boring Brick', 'artist' => 'Paramore'],
            [ 'title' => 'About You Now', 'artist' => 'Miranda Cosgrove'],
            [ 'title' => 'Real Love', 'artist' => 'Clean Bandit & Jess Glyne'],
            [ 'title' => 'Queen Of The Night', 'artist' => 'Whitney Houston'],
            [ 'title' => 'Lucky Star', 'artist' => 'Madonna'],
            [ 'title' => 'Good Girl', 'artist' => 'Carrie Underwood'],
            [ 'title' => 'WTF Do I Know', 'artist' => 'Miley Cyrus'],
            [ 'title' => 'Say So', 'artist' => 'Doja Cat'],
            [ 'title' => 'Soulmate', 'artist' => 'Lizzo'],
            [ 'title' => 'Bitch I\'m Madonna', 'artist' => 'Madonna'],
            [ 'title' => 'Hold My Hand', 'artist' => 'Jess Glyne'],
            [ 'title' => 'Not Myself Tonight', 'artist' => 'Christina Aguillera'],
            [ 'title' => 'Boys', 'artist' => 'Lizzo'],
            [ 'title' => 'Same Old Fool', 'artist' => 'Dolly Parton'],
            [ 'title' => 'Fantasy', 'artist' => 'Mariah Carey'],
            [ 'title' => 'What You Get Is What You See', 'artist' => 'Tina Turner'],
            [ 'title' => 'All About That Bass', 'artist' => 'Meghan Trainor'],
            [ 'title' => 'Edge Of Seventeen', 'artist' => 'Stevie Nicks'],
            [ 'title' => 'Chandelier', 'artist' => 'SIA'],
            [ 'title' => 'Comme Des Garçon', 'artist' => 'Rina Sawayama'],
            [ 'title' => 'See You Again', 'artist' => 'Miley Cyrus'],
            [ 'title' => 'Spice Up Your Life', 'artist' => 'Spice Girls'],
            [ 'title' => 'Tears Dry On Their Own', 'artist' => 'Amy Winehouse'],
            [ 'title' => 'Power', 'artist' => 'Little Mix'],
            [ 'title' => 'Miss You Much', 'artist' => 'Janet Jackson'],
            [ 'title' => 'Rain On Me', 'artist' => 'Lady Gaga ft. Ariana Grande'],
            [ 'title' => 'Stupid Love', 'artist' => 'Lady Gaga'],
            [ 'title' => 'Levitating', 'artist' => 'Dua Lipa'],
            [ 'title' => 'Vagina', 'artist' => 'CupcakKe'],
            [ 'title' => 'Wildest Dreams', 'artist' => 'Taylor Swift'],
            [ 'title' => 'good 4 u', 'artist' => 'Olivia Rodrigo'],
            [ 'title' => 'Telephone', 'artist' => 'Lady Gaga ft. Beyoncé'],
            [ 'title' => 'Physical', 'artist' => 'Dua Lipa'],
            [ 'title' => 'Conqueror', 'artist' => 'Estelle'],
            [ 'title' => 'Triste com T', 'artist' => 'Pabllo Vittar'],
            [ 'title' => 'Dance Again', 'artist' => 'Jenifer Lopez'],
            [ 'title' => 'Brutal', 'artist' => 'Olivia Rodrigo'],
            [ 'title' => 'Oh No!', 'artist' => 'MARINA'],
            [ 'title' => 'How You Like That', 'artist' => 'BLACKPINK'],
            [ 'title' => 'Focus', 'artist' => 'Ariana Grande'],
            [ 'title' => 'Stronger', 'artist' => 'Christina Aguillera'],
            [ 'title' => 'Domino', 'artist' => 'Jessie J'],
            [ 'title' => 'Salute', 'artist' => 'Little Mix'],
            [ 'title' => 'Scandalous', 'artist' => 'Mis-Teeq'],
            [ 'title' => 'Friday', 'artist' => 'Rebecca Black'],
            [ 'title' => 'Fantasy', 'artist' => 'Mariah Carey'],
            [ 'title' => 'All I Want For Christmas Is You', 'artist' => 'Mariah Carey'],
            [ 'title' => 'Raspberry Beret', 'artist' => 'Prince'],
            [ 'title' => 'Why Worry', 'artist' => 'Set It Off'],
            [ 'title' => 'Sweet Melody', 'artist' => 'Little Mix'],
            [ 'title' => 'Bittersweet', 'artist' => 'Fantasia'],
            [ 'title' => 'She Wolf', 'artist' => 'Shakira'],
            [ 'title' => 'Blame It On The Edit', 'artist' => 'RuPaul'],
            [ 'title' => 'Big Spender', 'artist' => 'Shirley Bassey'],
            [ 'title' => 'Turning Tables', 'artist' => 'Adele'],
            [ 'title' => 'How I Feel About You', 'artist' => 'Miranda Cosgrove'],
        ]);
    }
}
